version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name hy-handson --s3-location s3://hy-artfact/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src



